### ISSUE TITLE
Edit enities with new forms

### ISSUE THREAD

**Issue by MathijsC** [LitusProject/Litus#226]
Hi, there is a problem when you try to edit certain entities used in the system. For exaple: when you edit a shift, everything seems to work fine (the system returns an OK status). But when you look at the shift it isn't changed. The same thing happens with form fields.  The persistence when editing doesn't seem to work.

**Comment by bgotink** [comment]
I'm able to change the name, description, location, event, manager, number of volunteers, number of responsibles, unit, reward coins, edit roles and the dates of shifts.

Has this been fixed in the week since you've opened this issue?
If not, could you give more information on the exact circumstances where editing doesn't work?

**Comment by MathijsC** [comment]
I fixed those problems. Most of them you simply forgot to bind an entity to the edit form.
